language: php

sudo: false

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: COLLECT_COVERAGE=true
    - php: 7
    - php: hhvm

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then wget https://phar.phpunit.de/phpunit-4.8.27.phar && php phpunit-4.8.27.phar --coverage-text --coverage-clover=coverage.clover; else wget https://phar.phpunit.de/phpunit-4.8.27.phar && php phpunit-4.8.27.phar --no-coverage; fi

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
