language: php

sudo: false

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: COLLECT_COVERAGE=true
    - php: 7
    - php: hhvm

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then phpunit --coverage-clover=travis-tmp/coverage.clover; else phpunit; fi

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then wget -O travis-tmp/ocular.phar https://scrutinizer-ci.com/ocular.phar && php travis-tmp/ocular.phar code-coverage:upload --format=php-clover travis-tmp/coverage.clover; fi
